name: kampus_sggw
description: Kampus SGGW remastered
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  material_floating_search_bar: ^0.2.6
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  json_annotation: ^3.1.1
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  google_maps_flutter: ^2.0.3
  google_maps_flutter_web: ^0.3.0
  permission_handler: ^7.1.0
  fuzzy: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/map_objects/wzim.jpg
    - assets/json/map_items.json
    - assets/images/floors/floor_1.jpg
    - assets/images/icons/
  fonts:
    - family: SGGWMastro
      fonts:
        - asset: assets/fonts/SGGWMastro-Bold.ttf
          weight: 600
        - asset: assets/fonts/SGGWMastro-Italic.ttf
          style: italic
        - asset: assets/fonts/SGGWMastro-Regular.ttf
          weight: 400
    - family: SGGWSans
      fonts:
        - asset: assets/fonts/SGGWSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/SGGWSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/SGGWSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SGGWSans-Bold.ttf
          weight: 700
