name: kampus_sggw
description: Kampus SGGW remastered
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  material_floating_search_bar: ^0.2.6
  cupertino_icons: ^1.0.2
  url_launcher: ^5.7.10
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  json_serializable: ^3.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/map/map_z2.jpg
    - assets/translations/
    - assets/images/map_objects/wzim.jpg
    - assets/json/map_items.json
    - assets/json/search_history.json

